x-zou-build: &zou-build
    image: zou:${ZOU_VERSION:-latest}
    build:
        context: ./zou
        args:
            ZOU_VERSION: ${ZOU_VERSION:-latest}

services:
    kitsu:
        image: kitsu:${KITSU_VERSION:-latest}
        build:
            context: ./kitsu
            args:
                KITSU_VERSION: ${KITSU_VERSION:-latest}

    zou-app:
        <<: *zou-build

    zou-event:
        <<: *zou-build
       
    zou-jobs:
        <<: *zou-build
