version: '3.5'

x-base: &base
    restart: always
    networks:
        - internal

x-env: &env
    env_file:
        - ${ENV_FILE}

x-previews: &previews
    volumes:
        - 'previews:${PREVIEW_FOLDER}'

services:
    kitsu:
        <<: *base
        <<: *env
        container_name: ${COMPOSE_PROJECT_NAME}-kitsu
        image: registry.gitlab.com/mathbou/docker-cgwire/kitsu:$KITSU_VERSION
        depends_on:
            - zou-app
            - zou-event
            - zou-jobs
        ports:
            - '${PORT}:80'

    zou-app:
        <<: *base
        <<: *env
        container_name: ${COMPOSE_PROJECT_NAME}-zou-app
        image: registry.gitlab.com/mathbou/docker-cgwire/zou:$ZOU_VERSION
        depends_on:
          - db
        <<: *previews
        command: "gunicorn --error-logfile - --access-logfile - -w 3 -k gevent -b :5000 zou.app:app"

    zou-event:
        <<: *base
        <<: *env
        container_name: ${COMPOSE_PROJECT_NAME}-zou-event
        image: registry.gitlab.com/mathbou/docker-cgwire/zou:$ZOU_VERSION
        depends_on:
          - redis
        command: "gunicorn --error-logfile - --access-logfile - -w 1 -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -b :5001 zou.event_stream:app"

    zou-jobs:
        <<: *base
        <<: *env
        container_name: ${COMPOSE_PROJECT_NAME}-zou-jobs
        image: registry.gitlab.com/mathbou/docker-cgwire/zou:$ZOU_VERSION
        <<: *previews
        command: "rq worker -c zou.job_settings"

    db:
        <<: *base
        container_name: ${COMPOSE_PROJECT_NAME}-db-${DB_VERSION}
        image: postgres:${DB_VERSION}-alpine
        volumes:
            - 'db:/var/lib/postgresql/data'
            - ./db/pg_ctl.conf:/etc/postgresql/${DB_VERSION}/main/pg_ctl.conf:ro

    redis:
        <<: *base
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        image: redis:alpine
        volumes:
            - 'redis:/data'

volumes:
    db:
        name: ${COMPOSE_PROJECT_NAME}-db-${DB_VERSION}
    redis:
        name: ${COMPOSE_PROJECT_NAME}-redis
    previews:
        name: ${COMPOSE_PROJECT_NAME}-previews

networks:
    internal:
        name: ${COMPOSE_PROJECT_NAME}-internal
